server:
  port: 8085

bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    url: /test

    http-response-headers:
      hello: hi
    metrics:
      tags:
        - key: url
          expression: getRequestURI()
        - key: ip
          expression: getRemoteAddr()
    rate-limits:
    - bandwidths:
      - capacity: 5
        time: 2
        unit: minutes
      expression: "getHeader('X-FORWARDED-FOR')"
  - cache-name: buckets
    url: /test2
    metrics:
      tags:
        - key: url
          expression: getRequestURI()
    rate-limits:
      - bandwidths:
          - capacity: 7
            time: 1
            unit: minutes
management:
  endpoints.web.exposure.include: '*'

spring:
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
      config: classpath:hazelcast.xml

  cloud:
    gateway:
      routes:
        - id: path_route
          uri: https://example.org







